<a href="https://colab.research.google.com/github/vandit-11/learning-data-science/blob/main/titanic_survival_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [70]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeClassifier

In [71]:
import seaborn as sns

df = sns.load_dataset("titanic")
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [75]:
df['age'] = df['age'].fillna(
    df.groupby(['sex', 'adult_male'])['age'].transform('mean')
)

In [76]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          891 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [78]:
df[['sex', 'who']].drop_duplicates()

      sex    who
0    male    man
1  female  woman
7    male  child
9  female  child

In [79]:
df['who'].value_counts()

who
man      537
woman    271
child     83
Name: count, dtype: int64

Therefore, we would drop the column 'who' as it can be derived from age and sex columns.

In [80]:
df = df.drop(['who'], axis = 1)
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.000000,1,0,7.2500,S,Third,True,NaN,Southampton,no,False
1,1,1,female,38.000000,1,0,71.2833,C,First,False,C,Cherbourg,yes,False
2,1,3,female,26.000000,0,0,7.9250,S,Third,False,NaN,Southampton,yes,True
3,1,1,female,35.000000,1,0,53.1000,S,First,False,C,Southampton,yes,False
4,0,3,male,35.000000,0,0,8.0500,S,Third,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.000000,0,0,13.0000,S,Second,True,NaN,Southampton,no,True
887,1,1,female,19.000000,0,0,30.0000,S,First,False,B,Southampton,yes,True
888,0,3,female,27.915709,1,2,23.4500,S,Third,False,NaN,Southampton,no,False
889,1,1,male,26.000000,0,0,30.0000,C,First,True,C,Cherbourg,yes,True
890,0,3,male,32.000000,0,0,7.7500,Q,Third,True,NaN,Queenstown,no,True

In [81]:
df[['sex','age','adult_male']].drop_duplicates()

        sex   age  adult_male
0      male  22.0        True
1    female  38.0       False
2    female  26.0       False
3    female  35.0       False
4      male  35.0        True
..      ...   ...         ...
819    male  10.0       False
829  female  62.0       False
843    male  34.5        True
851    male  74.0        True
879  female  56.0       False

[147 rows x 3 columns]

The column adult_male is also redundant, therefore removing it too.

In [82]:
df = df.drop(['adult_male'], axis = 1)
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,deck,embark_town,alive,alone
0,0,3,male,22.000000,1,0,7.2500,S,Third,NaN,Southampton,no,False
1,1,1,female,38.000000,1,0,71.2833,C,First,C,Cherbourg,yes,False
2,1,3,female,26.000000,0,0,7.9250,S,Third,NaN,Southampton,yes,True
3,1,1,female,35.000000,1,0,53.1000,S,First,C,Southampton,yes,False
4,0,3,male,35.000000,0,0,8.0500,S,Third,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.000000,0,0,13.0000,S,Second,NaN,Southampton,no,True
887,1,1,female,19.000000,0,0,30.0000,S,First,B,Southampton,yes,True
888,0,3,female,27.915709,1,2,23.4500,S,Third,NaN,Southampton,no,False
889,1,1,male,26.000000,0,0,30.0000,C,First,C,Cherbourg,yes,True
890,0,3,male,32.000000,0,0,7.7500,Q,Third,NaN,Queenstown,no,True

In [83]:
df[['pclass','class']].drop_duplicates()

   pclass   class
0       3   Third
1       1   First
9       2  Second

In [84]:
df = df.drop(['class'], axis = 1)
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,deck,embark_town,alive,alone
0,0,3,male,22.000000,1,0,7.2500,S,NaN,Southampton,no,False
1,1,1,female,38.000000,1,0,71.2833,C,C,Cherbourg,yes,False
2,1,3,female,26.000000,0,0,7.9250,S,NaN,Southampton,yes,True
3,1,1,female,35.000000,1,0,53.1000,S,C,Southampton,yes,False
4,0,3,male,35.000000,0,0,8.0500,S,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.000000,0,0,13.0000,S,NaN,Southampton,no,True
887,1,1,female,19.000000,0,0,30.0000,S,B,Southampton,yes,True
888,0,3,female,27.915709,1,2,23.4500,S,NaN,Southampton,no,False
889,1,1,male,26.000000,0,0,30.0000,C,C,Cherbourg,yes,True
890,0,3,male,32.000000,0,0,7.7500,Q,NaN,Queenstown,no,True

In [85]:
df.embark_town.value_counts()

embark_town
Southampton    644
Cherbourg      168
Queenstown      77
Name: count, dtype: int64

The above column is also irrelevant, dropping it too.

In [86]:
df = df.drop(['embark_town'], axis = 1)
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,deck,alive,alone
0,0,3,male,22.000000,1,0,7.2500,S,NaN,no,False
1,1,1,female,38.000000,1,0,71.2833,C,C,yes,False
2,1,3,female,26.000000,0,0,7.9250,S,NaN,yes,True
3,1,1,female,35.000000,1,0,53.1000,S,C,yes,False
4,0,3,male,35.000000,0,0,8.0500,S,NaN,no,True
...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.000000,0,0,13.0000,S,NaN,no,True
887,1,1,female,19.000000,0,0,30.0000,S,B,yes,True
888,0,3,female,27.915709,1,2,23.4500,S,NaN,no,False
889,1,1,male,26.000000,0,0,30.0000,C,C,yes,True
890,0,3,male,32.000000,0,0,7.7500,Q,NaN,no,True

In [87]:
df[['survived', 'alive']].drop_duplicates()

   survived alive
0         0    no
1         1   yes

In [88]:
df = df.drop(['alive', 'embarked'], axis = 1)
df

     survived  pclass     sex        age  sibsp  parch     fare deck  alone
0           0       3    male  22.000000      1      0   7.2500  NaN  False
1           1       1  female  38.000000      1      0  71.2833    C  False
2           1       3  female  26.000000      0      0   7.9250  NaN   True
3           1       1  female  35.000000      1      0  53.1000    C  False
4           0       3    male  35.000000      0      0   8.0500  NaN   True
..        ...     ...     ...        ...    ...    ...      ...  ...    ...
886         0       2    male  27.000000      0      0  13.0000  NaN   True
887         1       1  female  19.000000      0      0  30.0000    B   True
888         0       3  female  27.915709      1      2  23.4500  NaN  False
889         1       1    male  26.000000      0      0  30.0000    C   True
890         0       3    male  32.000000      0      0   7.7500  NaN   True

[891 rows x 9 columns]

In [89]:
df[['survived','alone']].drop_duplicates().sort_values(by = ['survived', 'alone'])

   survived  alone
0         0  False
4         0   True
1         1  False
2         1   True

In [90]:
df.survived.value_counts()

survived
0    549
1    342
Name: count, dtype: int64

In [91]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  891 non-null    int64
 1   pclass    891 non-null    int64
 2   sex       891 non-null    object
 3   age       891 non-null    float64
 4   sibsp     891 non-null    int64
 5   parch     891 non-null    int64
 6   fare      891 non-null    float64
 7   deck      203 non-null    category
 8   alone     891 non-null    bool
dtypes: bool(1), category(1), float64(2), int64(4), object(1)
memory usage: 50.9+ KB

Since, deck is mostly null, let's drop it as well.

In [92]:
df = df.drop(['deck'], axis = 1)
df

     survived  pclass     sex        age  sibsp  parch     fare  alone
0           0       3    male  22.000000      1      0   7.2500  False
1           1       1  female  38.000000      1      0  71.2833  False
2           1       3  female  26.000000      0      0   7.9250   True
3           1       1  female  35.000000      1      0  53.1000  False
4           0       3    male  35.000000      0      0   8.0500   True
..        ...     ...     ...        ...    ...    ...      ...    ...
886         0       2    male  27.000000      0      0  13.0000   True
887         1       1  female  19.000000      0      0  30.0000   True
888         0       3  female  27.915709      1      2  23.4500  False
889         1       1    male  26.000000      0      0  30.0000   True
890         0       3    male  32.000000      0      0   7.7500   True

[891 rows x 8 columns]

In [93]:
df[['survived','parch']].drop_duplicates().sort_values(by = ['survived', 'parch'])

     survived  parch
0           0      0
7           0      1
27          0      2
86          0      3
167         0      4
13          0      5
678         0      6
1           1      0
10          1      1
8           1      2
437         1      3
25          1      5

In [95]:
from sklearn.preprocessing import LabelEncoder

In [96]:
le = LabelEncoder()

In [99]:
gender_le = le.fit_transform(df.sex)
gender_le[:5]

array([1, 0, 0, 0, 1])

In [101]:
df['gender_le'] = gender_le
df

,survived,pclass,sex,age,sibsp,parch,fare,alone,gender_le
0,0,3,male,22.000000,1,0,7.2500,False,1
1,1,1,female,38.000000,1,0,71.2833,False,0
2,1,3,female,26.000000,0,0,7.9250,True,0
3,1,1,female,35.000000,1,0,53.1000,False,0
4,0,3,male,35.000000,0,0,8.0500,True,1
...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.000000,0,0,13.0000,True,1
887,1,1,female,19.000000,0,0,30.0000,True,0
888,0,3,female,27.915709,1,2,23.4500,False,0
889,1,1,male,26.000000,0,0,30.0000,True,1
890,0,3,male,32.000000,0,0,7.7500,True,1

In [102]:
df[['sex', 'gender_le']].drop_duplicates()

      sex  gender_le
0    male          1
1  female          0

In [104]:
df = df.drop(['sex'], axis = 1)
df

KeyError: "['sex'] not found in axis"

In [106]:
df

     survived  pclass        age  sibsp  parch     fare  alone  gender_le
0           0       3  22.000000      1      0   7.2500  False          1
1           1       1  38.000000      1      0  71.2833  False          0
2           1       3  26.000000      0      0   7.9250   True          0
3           1       1  35.000000      1      0  53.1000  False          0
4           0       3  35.000000      0      0   8.0500   True          1
..        ...     ...        ...    ...    ...      ...    ...        ...
886         0       2  27.000000      0      0  13.0000   True          1
887         1       1  19.000000      0      0  30.0000   True          0
888         0       3  27.915709      1      2  23.4500  False          0
889         1       1  26.000000      0      0  30.0000   True          1
890         0       3  32.000000      0      0   7.7500   True          1

[891 rows x 8 columns]

In [109]:
df['alone_le'] = le.fit_transform(df.alone)
df

,survived,pclass,age,sibsp,parch,fare,alone,gender_le,alone_le
0,0,3,22.000000,1,0,7.2500,False,1,0
1,1,1,38.000000,1,0,71.2833,False,0,0
2,1,3,26.000000,0,0,7.9250,True,0,1
3,1,1,35.000000,1,0,53.1000,False,0,0
4,0,3,35.000000,0,0,8.0500,True,1,1
...,...,...,...,...,...,...,...,...,...
886,0,2,27.000000,0,0,13.0000,True,1,1
887,1,1,19.000000,0,0,30.0000,True,0,1
888,0,3,27.915709,1,2,23.4500,False,0,0
889,1,1,26.000000,0,0,30.0000,True,1,1
890,0,3,32.000000,0,0,7.7500,True,1,1

In [111]:
df = df.drop(['alone'], axis = 1)
df

     survived  pclass        age  sibsp  parch     fare  gender_le  alone_le
0           0       3  22.000000      1      0   7.2500          1         0
1           1       1  38.000000      1      0  71.2833          0         0
2           1       3  26.000000      0      0   7.9250          0         1
3           1       1  35.000000      1      0  53.1000          0         0
4           0       3  35.000000      0      0   8.0500          1         1
..        ...     ...        ...    ...    ...      ...        ...       ...
886         0       2  27.000000      0      0  13.0000          1         1
887         1       1  19.000000      0      0  30.0000          0         1
888         0       3  27.915709      1      2  23.4500          0         0
889         1       1  26.000000      0      0  30.0000          1         1
890         0       3  32.000000      0      0   7.7500          1         1

[891 rows x 8 columns]

In [112]:
X = df.iloc[:, 1:-1]
X

     pclass        age  sibsp  parch     fare  gender_le
0         3  22.000000      1      0   7.2500          1
1         1  38.000000      1      0  71.2833          0
2         3  26.000000      0      0   7.9250          0
3         1  35.000000      1      0  53.1000          0
4         3  35.000000      0      0   8.0500          1
..      ...        ...    ...    ...      ...        ...
886       2  27.000000      0      0  13.0000          1
887       1  19.000000      0      0  30.0000          0
888       3  27.915709      1      2  23.4500          0
889       1  26.000000      0      0  30.0000          1
890       3  32.000000      0      0   7.7500          1

[891 rows x 6 columns]

In [114]:
y = df.survived
y

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: survived, Length: 891, dtype: int64

In [115]:
from sklearn.model_selection import train_test_split

In [116]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [117]:
print(len(X_test), len(X_train))

179 712

In [118]:
model = DecisionTreeClassifier()

In [119]:
model.fit(X_train, y_train)

DecisionTreeClassifier()

In [120]:
model.score(X_train, y_train)

0.9803370786516854

In [121]:
model.score(X_test, y_test)

0.7821229050279329

In [127]:
model2 = DecisionTreeClassifier(max_depth=4)

In [128]:
model2.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=4)

In [129]:
model2.score(X_train, y_train)

0.8384831460674157

In [131]:
model2.score(X_test, y_test)

0.7988826815642458

In [132]:
model3 = DecisionTreeClassifier(min_samples_split=10)

In [133]:
model3.fit(X_train, y_train)

DecisionTreeClassifier(min_samples_split=10)

In [134]:
model3.score(X_train, y_train)

0.9101123595505618

In [135]:
model3.score(X_test, y_test)

0.8324022346368715